apiVersion: cert-manager.io/v1
kind: ClusterIssuer # I'm using ClusterIssuer here
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hofirma@gmail.com
    privateKeySecretRef:
      name: tls-secret
    solvers:
      - http01:
          ingress:
            ingressClassName: gce

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: cm-acme-http-solver
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: dev.cloud-workflow.com
#      http:
#        paths:
#          - path: /.well-known/acme-challenge/
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: cm-acme-http-solver
#                port:
#                  number: 8089